"""
This file is a cache of rules from modules/ruleList.
And it's automatically generalted by GitHub Action
"""

cache="""  - 404: Not Found,🤖 ChatBot
  - 404: Not Found,🤖 ChatBot
  - 404: Not Found,🎯 全球直连
  - 404: Not Found,🎯 全球直连
  - 404: Not Found,🛑 广告拦截
  - 404: Not Found,🍃 应用净化
  - 404: Not Found,🛑 广告拦截
  - 404: Not Found,🛑 广告拦截
  - 404: Not Found,🛡️ 隐私防护
  - 404: Not Found,📢 谷歌FCM
  - 404: Not Found,🎯 全球直连
  - 404: Not Found,Ⓜ️ 微软云盘
  - 404: Not Found,Ⓜ️ 微软服务
  - 404: Not Found,🍎 苹果服务
  - 404: Not Found,📲 电报消息
  - 404: Not Found,🎶 网易音乐
  - 404: Not Found,🎶 Spotify
  - 404: Not Found,🎮 游戏平台
  - 404: Not Found,🎮 游戏平台
  - 404: Not Found,🎮 游戏平台
  - 404: Not Found,🎮 游戏平台
  - 404: Not Found,🎮 游戏平台
  - 404: Not Found,📹 油管视频
  - 404: Not Found,🎥 奈飞视频
  - 404: Not Found,📺 巴哈姆特
  - 404: Not Found,📺 哔哩哔哩
  - 404: Not Found,📺 哔哩哔哩
  - 404: Not Found,🌏 国内媒体
  - 404: Not Found,🌍 国外媒体
  - 404: Not Found,🚀 节点选择
  - 404: Not Found,🎯 全球直连
  - 404: Not Found,🎯 全球直连
  - 404: Not Found,🎯 全球直连
  - 404: Not Found,🎯 全球直连
  - [Rule],Antifilter
  - DOMAIN-SUFFIX,10minutemail.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,1337x.to,Antifilter,PROXY
  - DOMAIN-SUFFIX,4pda.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,abook-club.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,abs-zero.twimg.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,abs.twimg.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,account-api.protonmail.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,account.protonmail.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,accounts.spotify.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,acf.international,Antifilter,PROXY
  - DOMAIN-SUFFIX,adguard.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,afcs.dellcdn.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,aftermarket.zf.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,agents.media,Antifilter,PROXY
  - DOMAIN-SUFFIX,agentura.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,alberta.ca,Antifilter,PROXY
  - DOMAIN-SUFFIX,anilibria.tv,Antifilter,PROXY
  - DOMAIN-SUFFIX,api.app.prod.grazie.aws.intellij.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,api.github.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,api.openai.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,api.protonmail.ch,Antifilter,PROXY
  - DOMAIN-SUFFIX,api.radarr.video,Antifilter,PROXY
  - DOMAIN-SUFFIX,api.themoviedb.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,api.twitter.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,aplawrence.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,app.m3u.in,Antifilter,PROXY
  - DOMAIN-SUFFIX,app.paraswap.io,Antifilter,PROXY
  - DOMAIN-SUFFIX,appstorrent.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,apt.releases.hashicorp.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,aqicn.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,artifacts.elastic.co,Antifilter,PROXY
  - DOMAIN-SUFFIX,atlassian.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,auth.grazie.ai,Antifilter,PROXY
  - DOMAIN-SUFFIX,auth0.openai.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,bard.google.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,bbc.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,bitbucket.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,bitcoin.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,bitru.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,boosteroid.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,bradyid.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,bt.t-ru.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,bt2.t-ru.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,bt3.t-ru.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,bt4.t-ru.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,builds.parsec.app,Antifilter,PROXY
  - DOMAIN-SUFFIX,canva.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,canva.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,carmasters.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,cdn.oaistatic.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,cdninstagram.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,certifytheweb.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,chat.openai.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,checkout.buckaroo.nl,Antifilter,PROXY
  - DOMAIN-SUFFIX,cherta.media,Antifilter,PROXY
  - DOMAIN-SUFFIX,chess.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,cisco.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,citrix.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,clamav.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,cloud.mongodb.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,cloudflare-dns.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,colta.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,community.cisco.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,crunchyroll.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,czx.to,Antifilter,PROXY
  - DOMAIN-SUFFIX,database.clamav.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,deezer.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,dell.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,deviantart.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,devops.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,dist.torproject.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,docker.elastic.co,Antifilter,PROXY
  - DOMAIN-SUFFIX,docs.redis.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,documentation.meraki.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,download.lenovo.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,doxajournal.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,dual-a-0001.a-msedge.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,dw.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,e1v-h.phncdn.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,edge.microsoft.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,edgeservices.bing.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,ehorussia.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,ej.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,euronews.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,event.on24.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,facebook.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,fb.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,fbcdn.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,fex.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,files.oaiusercontent.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,flibusta.is,Antifilter,PROXY
  - DOMAIN-SUFFIX,fluke.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,fork.pet,Antifilter,PROXY
  - DOMAIN-SUFFIX,forklog.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,formula1.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,forum.voynaplemyon.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,gallery.zetalliance.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,geni.us,Antifilter,PROXY
  - DOMAIN-SUFFIX,ggpht.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,gitlab.io,Antifilter,PROXY
  - DOMAIN-SUFFIX,gllto.glpals.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,gnome-look.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,golosameriki.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,googletagmanager.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,gordonua.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,grammarly.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,grazie.ai,Antifilter,PROXY
  - DOMAIN-SUFFIX,gulagu.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,hd.zetfix.online,Antifilter,PROXY
  - DOMAIN-SUFFIX,helm.releases.hashicorp.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,holod.global.ssl.fastly.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,holod.media,Antifilter,PROXY
  - DOMAIN-SUFFIX,hyperhost.ua,Antifilter,PROXY
  - DOMAIN-SUFFIX,ichef.bbci.co.uk,Antifilter,PROXY
  - DOMAIN-SUFFIX,iichan.hk,Antifilter,PROXY
  - DOMAIN-SUFFIX,image.tmdb.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,img.youtube.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,instagram.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,instagram.fhrk1-1.fna.fbcdn.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,instagram.fkun2-1.fna.fbcdn.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,instagram.frix7-1.fna.fbcdn.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,instagram.fvno2-1.fna.fbcdn.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,intel.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,istories.media,Antifilter,PROXY
  - DOMAIN-SUFFIX,kasparov.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,kavkaz-uzel.eu,Antifilter,PROXY
  - DOMAIN-SUFFIX,kemono.party,Antifilter,PROXY
  - DOMAIN-SUFFIX,kino.pub,Antifilter,PROXY
  - DOMAIN-SUFFIX,kinobase.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,kinokopilka.pro,Antifilter,PROXY
  - DOMAIN-SUFFIX,kinovod.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,kinozal.me,Antifilter,PROXY
  - DOMAIN-SUFFIX,kinozal.tv,Antifilter,PROXY
  - DOMAIN-SUFFIX,korrespondent.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,lenovo.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,lib.rus.ec,Antifilter,PROXY
  - DOMAIN-SUFFIX,libgen.rs,Antifilter,PROXY
  - DOMAIN-SUFFIX,linkedin.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,linuxiac.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,localbitcoins.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,lostfilm.run,Antifilter,PROXY
  - DOMAIN-SUFFIX,lostfilm.tv,Antifilter,PROXY
  - DOMAIN-SUFFIX,lostfilm.win,Antifilter,PROXY
  - DOMAIN-SUFFIX,m.strava.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,macpaw.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,macvendors.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,mail.protonmail.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,marketplace.atlassian.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,master.qt.io,Antifilter,PROXY
  - DOMAIN-SUFFIX,mattermost.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,mdza.io,Antifilter,PROXY
  - DOMAIN-SUFFIX,mediazona.ca,Antifilter,PROXY
  - DOMAIN-SUFFIX,mediazona.online,Antifilter,PROXY
  - DOMAIN-SUFFIX,medium.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,meduza.io,Antifilter,PROXY
  - DOMAIN-SUFFIX,megapeer.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,memohrc.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,metacritic.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,meteo.paraplan.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,monster.ie,Antifilter,PROXY
  - DOMAIN-SUFFIX,mouser.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,mrakopedia.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,mt.lv,Antifilter,PROXY
  - DOMAIN-SUFFIX,mult.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,my.atlassian.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,nasvsehtoshnit.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,navalny.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,netflix.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,news.google.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,newtimes.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,nih.gov,Antifilter,PROXY
  - DOMAIN-SUFFIX,nnmclub.to,Antifilter,PROXY
  - DOMAIN-SUFFIX,nordvpn.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,novayagazeta.eu,Antifilter,PROXY
  - DOMAIN-SUFFIX,novayagazeta.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,nyaa.si,Antifilter,PROXY
  - DOMAIN-SUFFIX,nyaa.tracker.wf,Antifilter,PROXY
  - DOMAIN-SUFFIX,oaistatic.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,oasis.app,Antifilter,PROXY
  - DOMAIN-SUFFIX,omv-extras.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,onlinesim.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,open.spotify.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,os.mbed.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,ovdinfo.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,packages.gitlab.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,pandasecurity.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,paperpaper.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,path3.xtracloud.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,patreon.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,pay.buckaroo.nl,Antifilter,PROXY
  - DOMAIN-SUFFIX,paypal.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,pb.wtf,Antifilter,PROXY
  - DOMAIN-SUFFIX,pbs.twimg.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,php.su,Antifilter,PROXY
  - DOMAIN-SUFFIX,piccy.info,Antifilter,PROXY
  - DOMAIN-SUFFIX,pixiv.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,platform.twitter.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,play.google.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,pornolab.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,portal.bgpmon.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,proekt.media,Antifilter,PROXY
  - DOMAIN-SUFFIX,protonmail.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,quora.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,radarr.servarr.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,radiosvoboda.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,raw-data.gitlab.io,Antifilter,PROXY
  - DOMAIN-SUFFIX,redis.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,refinitiv.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,registry.terraform.io,Antifilter,PROXY
  - DOMAIN-SUFFIX,releases.hashicorp.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,repo.mongodb.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,republic.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,resp.app,Antifilter,PROXY
  - DOMAIN-SUFFIX,rpm.grafana.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,ru.bellingcat.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,ru.depositphotos.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,ru.iherb.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,ru.krymr.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,rus-media.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,rus.delfi.lv,Antifilter,PROXY
  - DOMAIN-SUFFIX,rustorka.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,rutor.info,Antifilter,PROXY
  - DOMAIN-SUFFIX,rutor.is,Antifilter,PROXY
  - DOMAIN-SUFFIX,rutor.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,rutracker.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,rutracker.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,s3-1.amazonaws.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,saverudata.info,Antifilter,PROXY
  - DOMAIN-SUFFIX,saverudata.online,Antifilter,PROXY
  - DOMAIN-SUFFIX,sebeanus.online,Antifilter,PROXY
  - DOMAIN-SUFFIX,secure-web.cisco.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,seedoff.zannn.top,Antifilter,PROXY
  - DOMAIN-SUFFIX,semnasem.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,serpstat.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,skladchik.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,skyscanner.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,slideshare.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,soapui.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,sobesednik.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,soundcloud.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,spotify.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,st.kinovod.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,static-ss.xvideos-cdn.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,static.files.bbci.co.uk,Antifilter,PROXY
  - DOMAIN-SUFFIX,strava.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,stulchik.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,support.cambiumnetworks.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,support.huawei.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,support.ruckuswireless.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,svoboda.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,svtv.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,sydney.bing.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,sysdig.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,t.co,Antifilter,PROXY
  - DOMAIN-SUFFIX,tayga.info,Antifilter,PROXY
  - DOMAIN-SUFFIX,terraform.io,Antifilter,PROXY
  - DOMAIN-SUFFIX,theins.press,Antifilter,PROXY
  - DOMAIN-SUFFIX,theins.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,themoviedb.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,thepiratebay.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,tidal.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,timberland.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,tjournal.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,tmdb.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,tokenized.play.google.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,tools.cisco.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,torproject.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,torrent.by,Antifilter,PROXY
  - DOMAIN-SUFFIX,tr.anidub.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,tutanota.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,tvrain.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,twitter.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,underver.se,Antifilter,PROXY
  - DOMAIN-SUFFIX,unian.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,uniongang.tv,Antifilter,PROXY
  - DOMAIN-SUFFIX,velocidrone.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,verstka.media,Antifilter,PROXY
  - DOMAIN-SUFFIX,vhd.zetflix.online,Antifilter,PROXY
  - DOMAIN-SUFFIX,video.twimg.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,vipdrive.net,Antifilter,PROXY
  - DOMAIN-SUFFIX,vot-tak.tv,Antifilter,PROXY
  - DOMAIN-SUFFIX,vrv.co,Antifilter,PROXY
  - DOMAIN-SUFFIX,vyos.io,Antifilter,PROXY
  - DOMAIN-SUFFIX,watchguard.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,weather.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,weblance.com.ua,Antifilter,PROXY
  - DOMAIN-SUFFIX,welt.de,Antifilter,PROXY
  - DOMAIN-SUFFIX,wheather.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,wide-youtube.l.google.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,windguru.cz,Antifilter,PROXY
  - DOMAIN-SUFFIX,wixmp.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,wunderground.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.analog.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.bbc.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.cisco.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.citrix.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.currenttime.tv,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.dell.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.deviantart.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.dw.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.grammarly.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.hrw.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.intel.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.kavkazr.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.lenovo.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.lostfilmtv5.site,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.microchip.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.moscowtimes.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.postfix.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.qualcomm.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.smashwords.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.stalker2.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.the-village.ru,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.themoviedb.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.torproject.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.wikiart.org,Antifilter,PROXY
  - DOMAIN-SUFFIX,www.wunderground.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,xhamster.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,xhamsterlive.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,xiaomi.eu,Antifilter,PROXY
  - DOMAIN-SUFFIX,xnxx.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,xvideos.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,yt3.ggpht.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,ytimg.l.google.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,zetflix.online,Antifilter,PROXY
  - DOMAIN-SUFFIX,znanija.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,zohomail.com,Antifilter,PROXY
  - DOMAIN-SUFFIX,zona.media,Antifilter,PROXY
  - FINAL,DIRECT,Antifilter
  - GEOIP,CN,🎯 全球直连
  - MATCH,🐟 漏网之鱼"""